### ISSUE TITLE
Connecting to a Database error

### ISSUE THREAD

**Issue by vmarkaljon** [uakfdotb/gcb#44]
[SQL] Unable to connect to mysql database: Unknown character set index for field '255' received from server.
java.sql.SQLException: Unknown character set index for field '255' received from server.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
        at com.mysql.jdbc.ConnectionImpl.getCharsetNameForIndex(ConnectionImpl.java:3079)
        at com.mysql.jdbc.Field.<init>(Field.java:200)
        at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:763)
        at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:428)
        at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3131)
        at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2299)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2722)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2809)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2758)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1612)
        at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:4179)
        at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3582)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2531)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2301)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:317)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at gcb.bot.SQLThread.connection(SQLThread.java:98)
        at gcb.bot.SQLThread.add(SQLThread.java:234)
        at gcb.GChatBot.playerJoined(GChatBot.java:2078)
        at gcb.GarenaInterface.readGCRPLoop(GarenaInterface.java:1159)
        at gcb.GarenaThread.run(GarenaThread.java:34)

someonehelp me with this [SQL] Unable to connect to mysql database: Unknown character set index for field '255' received from server.

**Comment by vmarkaljon** [comment]
Please help I beg anyone? sir uakfdotb
this my last one problem to control my bot.
I try to change the root admins without using mysql but my Bot won't listen / know me rather.

**Comment by vmarkaljon** [comment]
Without Mysql
no Bot will follow my command please 👍
